name: Unit Tests
on: push
jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.0', '8.1']
        experimental: [false]
        include:
          - php-versions: '8.2'
            operating-system: 'ubuntu-latest'
            experimental: true
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout codebase
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring
        tools: composer:v2
    - name: Check PHP Version
      run: php --version
    - name: Check Composer Version
      run: composer --version
    - name: Composer Dependencies
      run: composer install --no-interaction --no-suggest --no-progress --prefer-dist --optimize-autoloader
    - name: Prepare build directory
      run: |
        [ ! -d build ] && (echo "creating build directory" && mkdir build)
    - name: Lint PHP Files
      run: vendor/bin/parallel-lint src
    - name: Run Testsuite
      run: vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/clover.xml
    - name: Upload coverage data
      run: |
        composer global require scrutinizer/ocular
        ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover build/clover.xml
